name: align_back_trans
owner: peterjc
homepage_url: https://github.com/peterjc/pico_galaxy/tree/master/tools/align_back_trans
remote_repository_url: https://github.com/peterjc/pico_galaxy/tree/master/tools/align_back_trans
description: Thread nucleotides onto a protein alignment (back-translation)
long_description: |
  Takes an input file of aligned protein sequences (typically FASTA or Clustal
  format), and a matching file of unaligned nucleotide sequences (FASTA format,
  using the same identifiers), and threads the nucleotide sequences onto the
  protein alignment to produce a codon aware nucleotide alignment - which can
  be viewed as a back translation.
categories:
- Fasta Manipulation
- Sequence Analysis
type: unrestricted
include:
- strip_components: 2
  source:
  - ../../test-data/demo_nuc_align.fasta
  - ../../test-data/demo_nucs.fasta
  - ../../test-data/demo_nucs_trailing_stop.fasta
  - ../../test-data/demo_prot_align.fasta
  - ../../tools/align_back_trans/README.rst
  - ../../tools/align_back_trans/align_back_trans.py
  - ../../tools/align_back_trans/align_back_trans.xml
  - ../../tools/align_back_trans/tool_dependencies.xml
