name: samtools_bam2fq
owner: peterjc
homepage_url: https://github.com/peterjc/pico_galaxy/tools/samtools_bam2fq
remote_repository_url: https://github.com/peterjc/pico_galaxy/tools/samtools_bam2fq
description: Convert SAM or BAM files to FASTQ using samtools bam2fq
long_description: |
  Currently this targets samtools v1.1 which fixes a number of issues with the bam2fq
  command in earlier versions (e.g. samtools v0.1.19).

  See https://github.com/peterjc/pico_galaxy/tree/master/tools/samtools_bam2fq
