name: samtools_bam2fq
owner: peterjc
homepage_url: http://www.htslib.org/
remote_repository_url: https://github.com/peterjc/pico_galaxy/tree/master/tools/samtools_bam2fq
description: Convert SAM or BAM files to FASTQ using samtools bam2fq
long_description: |
  Currently this targets samtools v1.1 which fixes a number of issues with the bam2fq
  command in earlier versions (e.g. samtools v0.1.19).
categories:
- Assembly
- Convert Formats
- Fastq Manipulation
- Next Gen Mappers
- SAM
type: unrestricted
include:
- strip_components: 2
  source:
  - ../../test-data/sam_spec_padded.bam
  - ../../test-data/sam_spec_padded.bam2fq.fastq
  - ../../test-data/sam_spec_padded.bam2fq_no_suf.fastq
  - ../../test-data/sam_spec_padded.bam2fq_pairs.fastq
  - ../../test-data/sam_spec_padded.bam2fq_singles.fastq
  - ../../test-data/sam_spec_padded.depad.bam
  - ../../test-data/sam_spec_padded.sam
  - ../../tools/samtools_bam2fq/README.rst
  - ../../tools/samtools_bam2fq/samtools_bam2fq.xml
  - ../../tools/samtools_bam2fq/tool_dependencies.xml
