name: fasta_filter_by_id
owner: peterjc
homepage_url: https://github.com/peterjc/pico_galaxy/tree/master/tools/fasta_filter_by_id
remote_repository_url: https://github.com/peterjc/pico_galaxy/tree/master/tools/fasta_filter_by_id
description: Filter FASTA sequences by ID (DEPRECATED)
long_description: |
  This tool is OBSOLETE, see my newer tool which supports multiple file formats:
  https://github.com/peterjc/pico_galaxy/tree/master/tools/seq_filter_by_id
  https://toolshed.g2.bx.psu.edu/view/peterjc/seq_filter_by_id/
categories:
- Fasta Manipulation
- Sequence Analysis
- Text Manipulation
type: unrestricted
include:
- strip_components: 2
  source:
  - ../../tools/fasta_filter_by_id/README.rst
  - ../../tools/fasta_filter_by_id/fasta_filter_by_id.py
  - ../../tools/fasta_filter_by_id/fasta_filter_by_id.xml
  - ../../tools/fasta_filter_by_id/tool_dependencies.xml
