name: seq_composition
owner: peterjc
homepage_url: https://github.com/peterjc/pico_galaxy/tools/seq_composition
remote_repository_url: https://github.com/peterjc/pico_galaxy/tools/seq_composition
description: Sequence composition
long_description: |
  Counts the letters in given sequence files, returning a table listing them
  with percentages. Suitable for use on assemblies or gene/protein sets.
  Probably not suitable for raw NGS reads.
categories:
- Sequence Analysis
type: unrestricted
