name: seq_composition
owner: peterjc
homepage_url: https://github.com/peterjc/pico_galaxy/tools/seq_composition
remote_repository_url: https://github.com/peterjc/pico_galaxy/tools/seq_composition
description: Sequence composition
long_description: |
  Counts the letters in given sequence files, returning a table listing them
  with percentages. Suitable for use on assemblies or gene/protein sets.
  Probably not suitable for raw NGS reads.
categories:
- Sequence Analysis
type: unrestricted
include:
- strip_components: 2
  source:
  - ../../test-data/MID4_GLZRM4E04_rnd30_frclip.sff
  - ../../test-data/MID4_GLZRM4E04_rnd30_frclip.seq_composition.tabular
  - ../../test-data/ecoli.fastq
  - ../../test-data/ecoli.seq_composition.tabular
  - ../../test-data/four_human_proteins.fasta
  - ../../test-data/four_human_proteins.seq_composition.tabular
  - ../../tools/seq_composition/README.rst
  - ../../tools/seq_composition/seq_composition.py
  - ../../tools/seq_composition/seq_composition.xml
  - ../../tools/seq_composition/tool_dependencies.xml
