name: mummer
owner: peterjc
homepage_url: http://mummer.sourceforge.net/
remote_repository_url: https://github.com/peterjc/pico_galaxy/tree/master/tools/mummer
description: Draw dotplots using mummer, mucmer, or promer with mummerplot
long_description: |
  A simple wrapper allowing MUMmer to be used to draw dotplots from within Galaxy.

  This offers alignment with mummer, mucmer, or promer which is then drawn with
  mummerplot giving PNG and PDF as output.
categories:
- Graphics
- Sequence Analysis
- Visualization
type: unrestricted
include:
- strip_components: 2
  source:
  - ../../test-data/magic.pdf
  - ../../test-data/magic.png
  - ../../test-data/rhodopsin_nucs.fasta
  - ../../test-data/three_human_mRNA.fasta
  - ../../tools/mummer/README.rst
  - ../../tools/mummer/mummer.py
  - ../../tools/mummer/mummer.xml
  - ../../tools/mummer/tool_dependencies.xml
