name: seq_primer_clip
owner: peterjc
homepage_url: https://github.com/peterjc/pico_galaxy/tools/seq_primer_clip
remote_repository_url: https://github.com/peterjc/pico_galaxy/tools/seq_primer_clip
description: Trim off 5' or 3' primers
long_description: |
  Takes reads in FASTA, FASTQ or SFF format and looks for the given primer sequences
  (within the existing clipped sequence) and further clips the reads to remove the
  primers and any preceding/trailing sequence. Supports forward and reverse primers,
  including IUPAC ambiguity codes.

  Note this tool was initially written for Roche 454 data, and should also work fine
  on Sanger or Ion Torrent as well. However, it is probably too slow for use on large
  Illumina datasets.
categories:
- Assembly
- Fasta Manipulation
- Text Manipulation
type: unrestricted
include:
- strip_components: 2
  source:
  - ../../test-data/MID4_GLZRM4E04_rnd30.fastqsanger
  - ../../test-data/MID4_GLZRM4E04_rnd30.sff
  - ../../test-data/MID4_GLZRM4E04_rnd30_fclip.fasta
  - ../../test-data/MID4_GLZRM4E04_rnd30_fclip.fastqsanger
  - ../../test-data/MID4_GLZRM4E04_rnd30_fclip.sff
  - ../../test-data/MID4_GLZRM4E04_rnd30_frclip.fasta
  - ../../test-data/MID4_GLZRM4E04_rnd30_frclip.fastqsanger
  - ../../test-data/MID4_GLZRM4E04_rnd30_frclip.sff
  - ../../test-data/dop_primers.fasta
  - ../../tools/seq_primer_clip/README.rst
  - ../../tools/seq_primer_clip/seq_primer_clip.py
  - ../../tools/seq_primer_clip/seq_primer_clip.xml
  - ../../tools/seq_primer_clip/tool_dependencies.xml
