name: samtools_depad
owner: peterjc
homepage_url: https://github.com/peterjc/pico_galaxy/tools/samtools_depad
remote_repository_url: https://github.com/peterjc/pico_galaxy/tools/samtools_depad
description: Re-align a SAM/BAM file with a padded reference (using samtools depad)
long_description: |
  Runs "samtools depad" to remap a SAM/BAM file using a padded reference (with
  gap characters) giving a new BAM file using an unpadded (ungapped) reference.
categories:
- Assembly
- SAM
- Sequence Analysis
type: unrestricted
include:
- strip_components: 2
  source:
  - ../../test-data/sam_spec_padded.bam
  - ../../test-data/sam_spec_padded.depad.bam
  - ../../test-data/sam_spec_padded.fasta
  - ../../test-data/sam_spec_padded.sam
  - ../../tools/samtools_depad/README.rst
  - ../../tools/samtools_depad/samtools_depad.py
  - ../../tools/samtools_depad/samtools_depad.xml
  - ../../tools/samtools_depad/tool_dependencies.xml
