name: secreted_protein_workflow
owner: peterjc
homepage_url: https://github.com/peterjc/pico_galaxy/tree/master/workflows/secreted_protein_workflow
remote_repository_url: https://github.com/peterjc/pico_galaxy/tree/master/workflows/secreted_protein_workflow
description: Indentify candidate secreted proteins using SignalP and TMHMM
long_description:
   This runs SignalP v3.0 (Bendtsen et al. 2004) and selects only proteins with a
   strong predicted signal peptide, and then runs TMHMM v2.0 (Krogh et al. 2001)
   on those, and selects only proteins without a predicted trans-membrane helix.
   This workflow was used in Kikuchi et al. (2011), and is a simplification of
   the candidate effector protocol described in Jones et al. (2009).
categories:
- Fasta Manipulation
- Sequence Analysis
type: unrestricted
