name: coverage_stats
owner: peterjc
homepage_url: https://github.com/peterjc/pico_galaxy/tree/master/tools/coverage_stats
remote_repository_url: https://github.com/peterjc/pico_galaxy/tree/master/tools/coverage_stats
description: BAM coverage statistics using samtools idxstats and depth
long_description: |
  This tool runs the commands ``samtools idxstats`` and ``samtools depth`` from
  the SAMtools toolkit, and parses their output to produce a consise summary of
  the coverage information for each reference sequence.
categories:
- Assembly
- SAM
type: unrestricted
include:
- strip_components: 2
  source:
  - ../../test-data/coverage_test.bam
  - ../../test-data/coverage_test.coverage_stats.tabular
  - ../../test-data/ex1.bam
  - ../../test-data/ex1.coverage_stats.tabular
  - ../../tools/coverage_stats/README.rst
  - ../../tools/coverage_stats/coverage_stats.xml
  - ../../tools/coverage_stats/coverage_stats.py
  - ../../tools/coverage_stats/tool_dependencies.xml
